/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ine5404.View;

import ine5404.Control.Controller;
import ine5404.Exception.EntradaDadosInvalidaException;
import ine5404.Model.Jogo;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chiqu
 */
public class TelaInicial extends javax.swing.JFrame {

    private Controller controller;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoInicio = new javax.swing.JButton();
        botaoNovoJogo = new javax.swing.JButton();
        botaoComoJogar = new javax.swing.JButton();
        Root = new javax.swing.JPanel();
        UITelaInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NovoJogo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinnerLinha = new javax.swing.JSpinner();
        spinnerColuna = new javax.swing.JSpinner();
        spinnerDificuldade = new javax.swing.JSpinner();
        spinnerNumeroPalavras = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoInicio.setText("Inicio");
        botaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicioActionPerformed(evt);
            }
        });

        botaoNovoJogo.setText("Novo Jogo");
        botaoNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoJogoActionPerformed(evt);
            }
        });

        botaoComoJogar.setText("Como jogar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoInicio)
                .addGap(60, 60, 60)
                .addComponent(botaoNovoJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoComoJogar)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInicio)
                    .addComponent(botaoNovoJogo)
                    .addComponent(botaoComoJogar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Root.setLayout(new java.awt.CardLayout());

        jLabel1.setText("BEM VINDO");

        javax.swing.GroupLayout UITelaInicioLayout = new javax.swing.GroupLayout(UITelaInicio);
        UITelaInicio.setLayout(UITelaInicioLayout);
        UITelaInicioLayout.setHorizontalGroup(
            UITelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UITelaInicioLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        UITelaInicioLayout.setVerticalGroup(
            UITelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UITelaInicioLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Root.add(UITelaInicio, "UITelaInicio");

        jButton1.setText("Começar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Linhas: ");

        jLabel3.setText("Colunas: ");

        jLabel4.setText("Dificuldade: ");

        jLabel5.setText("Número de palavras: ");

        spinnerLinha.setModel(new javax.swing.SpinnerNumberModel());

        spinnerColuna.setModel(new javax.swing.SpinnerNumberModel());

        spinnerDificuldade.setModel(new javax.swing.SpinnerListModel(new String[] {"Facil", "Medio", "Dificil"}));

        spinnerNumeroPalavras.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout NovoJogoLayout = new javax.swing.GroupLayout(NovoJogo);
        NovoJogo.setLayout(NovoJogoLayout);
        NovoJogoLayout.setHorizontalGroup(
            NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NovoJogoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NovoJogoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerNumeroPalavras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NovoJogoLayout.createSequentialGroup()
                        .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NovoJogoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovoJogoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(spinnerLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(spinnerColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))))
        );
        NovoJogoLayout.setVerticalGroup(
            NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NovoJogoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(NovoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spinnerNumeroPalavras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        Root.add(NovoJogo, "NovoJogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicioActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "UITelaInicio");
    }//GEN-LAST:event_botaoInicioActionPerformed

    private void botaoNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoJogoActionPerformed
        CardLayout card = (CardLayout) Root.getLayout();
        card.show(Root, "NovoJogo");
    }//GEN-LAST:event_botaoNovoJogoActionPerformed

    private void validaDadosEntrada() throws EntradaDadosInvalidaException {
        if ((int) spinnerLinha.getValue() <= 0) {
            throw new EntradaDadosInvalidaException("Linha não válida!");
        }
        if ((int) spinnerColuna.getValue() <= 0) {
            throw new EntradaDadosInvalidaException("Coluna não válida!");
        }
        if ((int) spinnerNumeroPalavras.getValue() <= 0) {
            throw new EntradaDadosInvalidaException("Número de palavras não é válido!");
        }
         if ((int) spinnerNumeroPalavras.getValue()%2 != 0) {
            throw new EntradaDadosInvalidaException("Número de palavras precisa ser par!");
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            validaDadosEntrada();

            List<Jogo.Dificuldade> dificuldades = new ArrayList();

            int linha = (int) spinnerLinha.getValue();
            int coluna = (int) spinnerColuna.getValue();
            int numeroPalavras = (int) spinnerNumeroPalavras.getValue();
            String dificuldade = (String) spinnerDificuldade.getValue();
            if (dificuldade.equals("Facil")) {
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorHorizontal);
            }
            if (dificuldade.equals("Medio")) {
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorHorizontal);
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorVertical);
            }
            if (dificuldade.equals("Dificil")) {
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorHorizontal);
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorVertical);
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorDiagonalPrincipal);
                dificuldades.add(Jogo.Dificuldade.EmbaralhadorDiagonalSecundaria);
            }

            Jogo novoJogo;
            novoJogo = new Jogo(linha, coluna, numeroPalavras, dificuldades);
            try {
                novoJogo.colocarPalavrasNoGrid();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "teste");
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            TelaJogo telaJogo = new TelaJogo(linha, coluna, novoJogo.getGrid(), this.controller);
            telaJogo.CriarLabels(novoJogo);
            telaJogo.CriarBotoes(novoJogo);
            telaJogo.CarregarPalavras(novoJogo);

        } catch (EntradaDadosInvalidaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NovoJogo;
    private javax.swing.JPanel Root;
    private javax.swing.JPanel UITelaInicio;
    private javax.swing.JButton botaoComoJogar;
    private javax.swing.JButton botaoInicio;
    private javax.swing.JButton botaoNovoJogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinnerColuna;
    private javax.swing.JSpinner spinnerDificuldade;
    private javax.swing.JSpinner spinnerLinha;
    private javax.swing.JSpinner spinnerNumeroPalavras;
    // End of variables declaration//GEN-END:variables
}
